export const NOTES = {
  GET_NOTES_SUCCESS: "GET_NOTES_SUCCESS",
  GET_NOTES_FAILURE: "GET_NOTES_FAILURE",
  SET_SELECTED_NOTE_ID: "SET_SELECTED_NOTE_ID",
  SET_SELECTED_NOTE: "SET_SELECTED_NOTE",
  ADD_NOTE_FAILURE: "ADD_NOTE_FAILURE",
  REMOVE_NOTE_FAILURE: "REMOVE_NOTE_FAILURE",
  UPDATE_NOTE_FAILURE: "UPDATE_NOTE_FAILURE"
};
